ALTER TABLE topicos
ADD COLUMN curso_id BIGINT;

UPDATE topicos
SET curso_id = 1;

ALTER TABLE topicos
ALTER COLUMN curso_id SET NOT NULL;

ALTER TABLE topicos
ADD CONSTRAINT fk_topicos_curso
FOREIGN KEY (curso_id)
REFERENCES cursos(id)
ON DELETE RESTRICT;

ALTER TABLE topicos
DROP COLUMN curso;

ALTER TABLE topicos
ADD COLUMN fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;